export const apiRoutes = {
  transactions: '/transactions',
  expenses: '/expenses',
  categories: '/categories',
  accounts: '/accounts',
  parseInput: '/ai/parse-input',
  health: '/health',
  financialAdvisorChat: '/api/chat/financial-advisor',
  financialAdvisorChatStream: '/api/chat/financial-advisor/stream',
  wealthPositions: '/wealth/positions',
  wealthContributions: '/wealth/contributions',
  financialSummary: '/analytics/financial-summary',
  fireEssentialCategories: '/fire/essential-categories',
  fireProfile: '/fire/profile',
  fireCalculate: '/fire/calculate',
  fireScenario: '/fire/scenario',
} as const;
